apiVersion: app/v1
kind: Deployment
metadata:
  name: vpromc
  labels:
    app: vpromc

spec:
  selector:
    matchlabels:
      app: vpromc
  replicas: 1
  template:
    spec:
      containers:
        - name: vpromc
          image: memcached
          ports:
            - name: vpromc-port
              containerPort: 11211

